//LAB 3 - ARRAYS & LOOPS - PART 2


//TEAM MEMBER ARRAY
ourTeam = ["Mayuresh", "Tarun", "Dhara", "Saurabhi", "Pallavi"];

//OUTPUT TEAM ARRAY TO JS CONSOLE


//REMOVE LAST MEMBER


//ADD SEAN TO FRONT OF ARRAY


//REARRANGE THE ARRAY ALPHABETICALLY


//OUTPUT REQUIRED MESSAGE TO JS CONSOLE


//LOOP THROUGH ARRAY TO OUTPUT TEAM MEMBERS/NUMBERS TO JS CONSOLE

